// Reference-to-patch analysis — the reverse direction of the DSP architect.
//
// Measures the tonal balance of audio the creator already loves, so a patch can
// be DERIVED from a reference instead of described from scratch.
//
// Deliberately local Web Audio, not sonicAnalyze: that endpoint only reports BPM
// and lyric alignment for clips generated by our own service, so it cannot profile
// an arbitrary reference file and reports nothing about tone. Analysing in the
// browser also means an arbitrary reference costs no credits and never leaves the
// creator's machine.
//
// This produces a DESCRIPTION of a reference, never a copy of it: band levels and
// a centroid cannot reconstruct source audio, so a derived patch is a tone target,
// not a derivative work.

// Octave-ish mastering bands. Edges match the vocabulary the architect already
// reasons in (sub / mud / presence / air) so the profile is directly actionable.
const BANDS = [
  { key: 'sub',     label: 'Sub',      lo: 20,    hi: 60 },
  { key: 'low',     label: 'Low',      lo: 60,    hi: 160 },
  { key: 'low_mid', label: 'Low-mid',  lo: 160,   hi: 500 },
  { key: 'mid',     label: 'Mid',      lo: 500,   hi: 1500 },
  { key: 'high_mid',label: 'High-mid', lo: 1500,  hi: 4000 },
  { key: 'high',    label: 'High',     lo: 4000,  hi: 9000 },
  { key: 'air',     label: 'Air',      lo: 9000,  hi: 18000 },
];

const ANALYSIS_SECONDS = 20;

function rms(channel) {
  let sum = 0;
  for (let i = 0; i < channel.length; i++) sum += channel[i] * channel[i];
  return Math.sqrt(sum / channel.length) || 1e-9;
}

function peak(channel) {
  let max = 0;
  for (let i = 0; i < channel.length; i++) {
    const v = Math.abs(channel[i]);
    if (v > max) max = v;
  }
  return max || 1e-9;
}

const toDb = (v) => 20 * Math.log10(Math.max(v, 1e-9));

/** Take a representative slice from the middle — intros and fades misrepresent a mix. */
function centerSlice(buffer, seconds) {
  const want = Math.min(Math.floor(seconds * buffer.sampleRate), buffer.length);
  const start = Math.max(0, Math.floor((buffer.length - want) / 2));
  const out = { length: want, sampleRate: buffer.sampleRate, channels: [] };
  for (let c = 0; c < buffer.numberOfChannels; c++) {
    out.channels.push(buffer.getChannelData(c).subarray(start, start + want));
  }
  return out;
}

function monoOf(slice) {
  if (slice.channels.length === 1) return slice.channels[0];
  const [l, r] = slice.channels;
  const mono = new Float32Array(slice.length);
  for (let i = 0; i < slice.length; i++) mono[i] = (l[i] + r[i]) / 2;
  return mono;
}

/** RMS of one band, measured by rendering the slice through a band-limited pair. */
async function bandRms(mono, sampleRate, lo, hi) {
  const ctx = new OfflineAudioContext(1, mono.length, sampleRate);
  const buf = ctx.createBuffer(1, mono.length, sampleRate);
  buf.copyToChannel(mono, 0);

  const src = ctx.createBufferSource();
  src.buffer = buf;

  const hp = ctx.createBiquadFilter();
  hp.type = 'highpass';
  hp.frequency.value = lo;
  const lp = ctx.createBiquadFilter();
  lp.type = 'lowpass';
  lp.frequency.value = Math.min(hi, sampleRate / 2 - 100);

  src.connect(hp).connect(lp).connect(ctx.destination);
  src.start(0);
  const rendered = await ctx.startRendering();
  return rms(rendered.getChannelData(0));
}

/**
 * Analyse a decoded AudioBuffer into a compact, LLM-readable tonal profile.
 * Band levels are RELATIVE (dB against the loudest band) so the profile describes
 * balance rather than how loud the reference was mastered — otherwise every quiet
 * reference would read as "dark".
 */
export async function profileAudioBuffer(buffer) {
  const slice = centerSlice(buffer, ANALYSIS_SECONDS);
  const mono = monoOf(slice);

  const raw = [];
  for (const b of BANDS) {
    raw.push(await bandRms(mono, slice.sampleRate, b.lo, b.hi));
  }
  const loudest = Math.max(...raw);

  const bands = BANDS.map((b, i) => ({
    key: b.key,
    label: b.label,
    range_hz: `${b.lo}-${b.hi}`,
    relative_db: Math.round((toDb(raw[i]) - toDb(loudest)) * 10) / 10,
  }));

  // Energy-weighted band centre — a coarse brightness figure, honestly labelled
  // as approximate because it is derived from 7 bands, not a full spectrum.
  const totalEnergy = raw.reduce((a, v) => a + v, 0);
  const centroid = raw.reduce(
    (acc, v, i) => acc + v * Math.sqrt(BANDS[i].lo * BANDS[i].hi), 0,
  ) / (totalEnergy || 1);

  const fullRms = rms(mono);
  const crestDb = Math.round((toDb(peak(mono)) - toDb(fullRms)) * 10) / 10;

  let stereoWidth = 0;
  if (slice.channels.length > 1) {
    const [l, r] = slice.channels;
    const side = new Float32Array(slice.length);
    for (let i = 0; i < slice.length; i++) side[i] = (l[i] - r[i]) / 2;
    stereoWidth = Math.round((rms(side) / fullRms) * 100) / 100;
  }

  return {
    bands,
    approx_centroid_hz: Math.round(centroid),
    crest_factor_db: crestDb,
    stereo_width: stereoWidth,
    analysed_seconds: Math.round((slice.length / slice.sampleRate) * 10) / 10,
    source_duration_seconds: Math.round(buffer.duration * 10) / 10,
  };
}

/** Decode a local File (never uploaded) and profile it. */
export async function profileReferenceFile(file) {
  const ctx = new (window.AudioContext || window.webkitAudioContext)();
  const decoded = await ctx.decodeAudioData(await file.arrayBuffer());
  const profile = await profileAudioBuffer(decoded);
  ctx.close();
  return profile;
}

/** Short human-readable read of the profile, for the panel. */
export function describeProfile(profile) {
  const c = profile.approx_centroid_hz;
  const tone = c < 700 ? 'dark and low-centred' : c < 1600 ? 'balanced, mid-centred' : c < 3000 ? 'forward and bright' : 'very bright / airy';
  const dyn = profile.crest_factor_db < 8 ? 'heavily compressed' : profile.crest_factor_db < 14 ? 'moderately dynamic' : 'open and dynamic';
  const width = profile.stereo_width > 0.35 ? 'wide' : profile.stereo_width > 0.12 ? 'moderately wide' : 'narrow / near-mono';
  return `${tone}, ${dyn}, ${width}`;
}