// Curated Cover Song presets. Each preset fills as many Cover Studio fields
// as possible in one tap. Fields left undefined are intentionally not touched
// (user can fine-tune after applying).
//
// Schema per preset:
//   id           string — unique key
//   name         string — display name
//   emoji        string — single emoji for the card
//   category     'mood' | 'genre' | 'novelty' | 'era' | 'fusion'
//   description  string — one-line vibe summary
//   fields:
//     title_suffix       string — appended to source name to form a title
//     genre              string
//     mood               string
//     tags               string (comma-separated style descriptors)
//     negative_tags      string
//     vocal_gender       '' | 'f' | 'm'
//     instrumental       boolean
//     ai_description     string — for AI Description mode
//     style_weight       0-1
//     audio_weight       0-1
//     weirdness          0-1
//     custom_mode_pref   'lyrics' | 'ai'  — which tab to switch to

export const COVER_PRESETS = [
  // ── NOVELTY / CHARACTER ───────────────────────────────────────────────────
  {
    id: 'comic-cartoon',
    name: 'Comic Cartoon',
    emoji: '💥',
    category: 'novelty',
    description: 'Saturday-morning cartoon energy — bouncy, silly, kazoo-and-tuba',
    fields: {
      title_suffix: '(Cartoon Cover)',
      genre: 'comedy cartoon pop',
      mood: 'playful, goofy, upbeat',
      tags: 'kazoo, tuba, slide whistle, cartoon foley, bouncy bass, vaudeville piano, hand claps',
      negative_tags: 'serious, dark, autotune, trap drums',
      vocal_gender: '',
      instrumental: false,
      ai_description: 'A goofy cartoon-style cover with kazoos, slide whistles, bouncy tuba bass, and over-the-top comedic vocal delivery. Like a Saturday-morning cartoon theme.',
      style_weight: 0.85, audio_weight: 0.35, weirdness: 0.7,
      custom_mode_pref: 'ai',
    },
  },
  {
    id: 'dark-villain',
    name: 'Dark Villain',
    emoji: '🦇',
    category: 'novelty',
    description: 'Gothic, sinister, brooding — symphonic horror score',
    fields: {
      title_suffix: '(Dark Version)',
      genre: 'gothic symphonic',
      mood: 'sinister, brooding, ominous',
      tags: 'orchestral strings, pipe organ, choral pads, deep bass, distorted guitar, slow tempo, minor key',
      negative_tags: 'happy, bright, major key, upbeat',
      vocal_gender: 'm',
      instrumental: false,
      ai_description: 'A dark, gothic cover with ominous orchestral strings, pipe organ, ghostly choir pads, and brooding baritone vocals. Cinematic villain-theme energy.',
      style_weight: 0.8, audio_weight: 0.4, weirdness: 0.55,
      custom_mode_pref: 'ai',
    },
  },
  {
    id: 'parody-comedy',
    name: 'Parody / Spoof',
    emoji: '🤪',
    category: 'novelty',
    description: 'Weird-Al style parody — same melody, absurd lyrics',
    fields: {
      title_suffix: '(Parody)',
      genre: 'comedy parody',
      mood: 'absurd, humorous, tongue-in-cheek',
      tags: 'accordion, polka beat, novelty horns, exaggerated vocal delivery, comedic timing',
      negative_tags: 'serious, somber, dark',
      vocal_gender: 'm',
      instrumental: false,
      ai_description: 'A Weird-Al style parody cover — same iconic melody, absurd comedic lyrics about everyday mundane things, accordion and polka beats underneath.',
      style_weight: 0.7, audio_weight: 0.5, weirdness: 0.85,
      custom_mode_pref: 'ai',
    },
  },
  {
    id: 'kids-singalong',
    name: 'Kids Singalong',
    emoji: '🧸',
    category: 'novelty',
    description: 'Wholesome, simple, child-friendly singalong',
    fields: {
      title_suffix: '(Kids Version)',
      genre: 'childrens music',
      mood: 'cheerful, wholesome, innocent',
      tags: 'ukulele, glockenspiel, soft hand drums, childrens choir, simple melody, claps',
      negative_tags: 'explicit, dark, heavy, distortion',
      vocal_gender: 'f',
      instrumental: false,
      ai_description: 'A wholesome kids-singalong cover with ukulele, glockenspiel, a friendly female lead, and a cheerful childrens choir on the chorus.',
      style_weight: 0.75, audio_weight: 0.45, weirdness: 0.2,
      custom_mode_pref: 'ai',
    },
  },
  {
    id: 'epic-trailer',
    name: 'Epic Movie Trailer',
    emoji: '🎬',
    category: 'novelty',
    description: 'Hans-Zimmer-style cinematic trailer rework',
    fields: {
      title_suffix: '(Epic Trailer Mix)',
      genre: 'cinematic orchestral',
      mood: 'epic, heroic, dramatic',
      tags: 'massive orchestral strings, taiko drums, brass stabs, choir, slow build, huge dynamic range',
      negative_tags: 'lo-fi, casual, intimate',
      vocal_gender: '',
      instrumental: true,
      ai_description: 'A massive cinematic trailer-style instrumental cover with thundering taiko drums, soaring strings, brass stabs, and an epic choir on the climax.',
      style_weight: 0.85, audio_weight: 0.5, weirdness: 0.3,
      custom_mode_pref: 'ai',
    },
  },

  // ── GENRE FLIPS ───────────────────────────────────────────────────────────
  {
    id: 'acoustic-folk',
    name: 'Acoustic Folk',
    emoji: '🪕',
    category: 'genre',
    description: 'Intimate fingerstyle guitar and warm vocals',
    fields: {
      title_suffix: '(Acoustic)',
      genre: 'indie folk',
      mood: 'warm, intimate, melancholic',
      tags: 'fingerstyle guitar, soft brushed drums, mandolin, warm vocals, room ambience, vinyl crackle',
      negative_tags: 'electronic drums, autotune, synth',
      vocal_gender: 'f',
      instrumental: false,
      ai_description: 'An intimate acoustic indie-folk cover with fingerstyle guitar, soft mandolin, warm female vocals, and gentle room ambience.',
      style_weight: 0.7, audio_weight: 0.55, weirdness: 0.25,
      custom_mode_pref: 'ai',
    },
  },
  {
    id: 'lo-fi-chill',
    name: 'Lo-Fi Chill',
    emoji: '🎧',
    category: 'genre',
    description: 'Late-night study beats — vinyl crackle, jazz chords',
    fields: {
      title_suffix: '(Lo-Fi)',
      genre: 'lo-fi hip hop',
      mood: 'chill, nostalgic, dreamy',
      tags: 'vinyl crackle, dusty drums, jazz piano chords, warm bass, tape saturation, mellow',
      negative_tags: 'aggressive, bright, EDM, trap',
      vocal_gender: '',
      instrumental: true,
      ai_description: 'A lo-fi hip-hop cover with dusty drum samples, mellow jazz piano chords, vinyl crackle, and warm tape-saturated bass. Late-night study vibes.',
      style_weight: 0.75, audio_weight: 0.5, weirdness: 0.3,
      custom_mode_pref: 'ai',
    },
  },
  {
    id: 'synthwave',
    name: 'Synthwave',
    emoji: '🌆',
    category: 'genre',
    description: '80s retro neon — analog synths and gated reverb',
    fields: {
      title_suffix: '(Synthwave Remix)',
      genre: 'synthwave',
      mood: 'nostalgic, neon, driving',
      tags: 'analog synth lead, juno pad, gated reverb drums, sidechain bass, arpeggio, 80s production',
      negative_tags: 'acoustic, organic drums, country',
      vocal_gender: 'm',
      instrumental: false,
      ai_description: 'A neon-soaked synthwave cover with analog Juno pads, driving arpeggios, gated reverb drums, and a confident male vocal. Pure 80s nostalgia.',
      style_weight: 0.8, audio_weight: 0.45, weirdness: 0.35,
      custom_mode_pref: 'ai',
    },
  },
  {
    id: 'trap-hiphop',
    name: 'Trap Hip-Hop',
    emoji: '🔥',
    category: 'genre',
    description: 'Modern trap — 808s, hi-hats, dark synths',
    fields: {
      title_suffix: '(Trap Remix)',
      genre: 'trap hip-hop',
      mood: 'hard, dark, confident',
      tags: '808 bass, rolling hi-hats, dark piano, snare claps, vocal chops, modern production',
      negative_tags: 'acoustic, soft, lo-fi',
      vocal_gender: 'm',
      instrumental: false,
      ai_description: 'A hard-hitting trap cover with sliding 808 bass, rolling hi-hats, dark cinematic piano, and confident rap-sung vocals.',
      style_weight: 0.8, audio_weight: 0.45, weirdness: 0.4,
      custom_mode_pref: 'ai',
    },
  },
  {
    id: 'metal-shred',
    name: 'Metal Shred',
    emoji: '🤘',
    category: 'genre',
    description: 'Heavy distortion, double-kick, shredding leads',
    fields: {
      title_suffix: '(Metal Cover)',
      genre: 'metal',
      mood: 'aggressive, heavy, powerful',
      tags: 'distorted guitars, double kick drums, shredding solos, growling bass, powerful vocals, drop D tuning',
      negative_tags: 'acoustic, soft, electronic, ballad',
      vocal_gender: 'm',
      instrumental: false,
      ai_description: 'An aggressive metal cover with heavily distorted guitars, double-kick drums, shredding solos, and powerful male vocals.',
      style_weight: 0.8, audio_weight: 0.4, weirdness: 0.4,
      custom_mode_pref: 'ai',
    },
  },
  {
    id: 'edm-festival',
    name: 'EDM Festival',
    emoji: '🎆',
    category: 'genre',
    description: 'Main-stage drop with euphoric leads',
    fields: {
      title_suffix: '(EDM Drop)',
      genre: 'progressive house EDM',
      mood: 'euphoric, energetic, uplifting',
      tags: 'big room drops, supersaw leads, four-on-the-floor kick, sidechain bass, festival energy, build-ups',
      negative_tags: 'acoustic, lo-fi, somber',
      vocal_gender: 'f',
      instrumental: false,
      ai_description: 'A euphoric EDM festival cover with big-room drops, supersaw leads, sidechain-pumped bass, and soaring female vocals on the build.',
      style_weight: 0.8, audio_weight: 0.4, weirdness: 0.4,
      custom_mode_pref: 'ai',
    },
  },
  {
    id: 'country',
    name: 'Country',
    emoji: '🤠',
    category: 'genre',
    description: 'Modern Nashville — slide guitar and harmonies',
    fields: {
      title_suffix: '(Country Version)',
      genre: 'modern country',
      mood: 'heartfelt, warm, anthemic',
      tags: 'acoustic guitar, pedal steel, slide guitar, Nashville drums, harmony vocals, mandolin',
      negative_tags: 'trap drums, autotune, EDM',
      vocal_gender: 'm',
      instrumental: false,
      ai_description: 'A modern Nashville country cover with acoustic guitar, pedal steel, slide guitar fills, tight harmony vocals, and a heartfelt male lead.',
      style_weight: 0.75, audio_weight: 0.5, weirdness: 0.25,
      custom_mode_pref: 'ai',
    },
  },
  {
    id: 'jazz-lounge',
    name: 'Jazz Lounge',
    emoji: '🎷',
    category: 'genre',
    description: 'Smoky lounge jazz with brushed drums and sax',
    fields: {
      title_suffix: '(Jazz Lounge)',
      genre: 'jazz lounge',
      mood: 'smooth, sultry, late-night',
      tags: 'walking upright bass, brushed drums, tenor saxophone, jazz piano comping, smoky vocals, swing feel',
      negative_tags: 'electronic, distortion, fast tempo',
      vocal_gender: 'f',
      instrumental: false,
      ai_description: 'A smoky jazz lounge cover with walking upright bass, brushed drums, tenor sax solos, and a sultry female lead. Late-night cocktail bar energy.',
      style_weight: 0.75, audio_weight: 0.5, weirdness: 0.3,
      custom_mode_pref: 'ai',
    },
  },
  {
    id: 'reggae',
    name: 'Reggae',
    emoji: '🌴',
    category: 'genre',
    description: 'One-drop reggae groove with island vibes',
    fields: {
      title_suffix: '(Reggae Version)',
      genre: 'reggae',
      mood: 'laid-back, sunny, positive',
      tags: 'one-drop drums, off-beat skank guitar, deep dub bass, organ bubble, horn section, island vibes',
      negative_tags: 'aggressive, dark, EDM, trap',
      vocal_gender: 'm',
      instrumental: false,
      ai_description: 'A laid-back reggae cover with one-drop drums, off-beat skank guitar, deep dub bass, bubbling organ, and a warm male lead vocal.',
      style_weight: 0.75, audio_weight: 0.5, weirdness: 0.3,
      custom_mode_pref: 'ai',
    },
  },
  {
    id: 'kpop',
    name: 'K-Pop',
    emoji: '✨',
    category: 'genre',
    description: 'Glossy K-pop production with bright synths',
    fields: {
      title_suffix: '(K-Pop Version)',
      genre: 'k-pop',
      mood: 'bright, energetic, polished',
      tags: 'bright synth leads, tight 808s, vocal stacks, sparkling pads, modern pop production, sidechain',
      negative_tags: 'lo-fi, dark, acoustic',
      vocal_gender: 'f',
      instrumental: false,
      ai_description: 'A glossy K-pop cover with bright synth leads, tight 808s, stacked harmony vocals, sparkling pads, and a polished female lead.',
      style_weight: 0.8, audio_weight: 0.4, weirdness: 0.4,
      custom_mode_pref: 'ai',
    },
  },

  // ── ERAS ──────────────────────────────────────────────────────────────────
  {
    id: '80s-pop',
    name: '80s Pop',
    emoji: '📼',
    category: 'era',
    description: 'Big hair, gated reverb, DX7 bells',
    fields: {
      title_suffix: '(80s Version)',
      genre: '80s pop',
      mood: 'nostalgic, anthemic, bright',
      tags: 'gated reverb snare, DX7 electric piano, FM bells, slap bass, sax solo, big hair production',
      negative_tags: 'modern trap, lo-fi, autotune',
      vocal_gender: 'f',
      instrumental: false,
      ai_description: 'An 80s pop cover with gated reverb snares, DX7 electric pianos, FM bells, slap bass, and an anthemic female lead. Pure 1985 energy.',
      style_weight: 0.8, audio_weight: 0.45, weirdness: 0.35,
      custom_mode_pref: 'ai',
    },
  },
  {
    id: '90s-grunge',
    name: '90s Grunge',
    emoji: '🎸',
    category: 'era',
    description: 'Distorted guitars, raw vocals, Seattle sound',
    fields: {
      title_suffix: '(Grunge Cover)',
      genre: '90s grunge',
      mood: 'raw, angsty, gritty',
      tags: 'distorted guitars, heavy bass, raw drums, gravelly vocals, flannel-era production, drop D',
      negative_tags: 'polished, electronic, autotune',
      vocal_gender: 'm',
      instrumental: false,
      ai_description: 'A raw 90s grunge cover with thick distorted guitars, heavy bass, pounding drums, and a gravelly angsty male lead. Pure Seattle 1993.',
      style_weight: 0.8, audio_weight: 0.45, weirdness: 0.35,
      custom_mode_pref: 'ai',
    },
  },
  {
    id: 'medieval-bard',
    name: 'Medieval Bard',
    emoji: '🏰',
    category: 'era',
    description: 'Lute, recorder, hand drums — tavern singalong',
    fields: {
      title_suffix: '(Medieval Bard Version)',
      genre: 'medieval folk',
      mood: 'rustic, festive, tavern',
      tags: 'lute, recorder, hand drums, hurdy-gurdy, tambourine, modal harmony, tavern singalong',
      negative_tags: 'electronic, modern drums, autotune',
      vocal_gender: 'm',
      instrumental: false,
      ai_description: 'A medieval bard cover with lute, recorder, hand drums, hurdy-gurdy, and a festive male lead. Like a tavern singalong in 1350.',
      style_weight: 0.85, audio_weight: 0.4, weirdness: 0.55,
      custom_mode_pref: 'ai',
    },
  },

  // ── FUSIONS ───────────────────────────────────────────────────────────────
  {
    id: 'orchestral-piano',
    name: 'Orchestral Piano',
    emoji: '🎹',
    category: 'fusion',
    description: 'Cinematic piano-led arrangement with strings',
    fields: {
      title_suffix: '(Piano Orchestral)',
      genre: 'cinematic piano',
      mood: 'emotional, sweeping, intimate',
      tags: 'grand piano, lush strings, sustain pedal, slow build, cello solo, cinematic dynamics',
      negative_tags: 'drums, electronic, trap',
      vocal_gender: '',
      instrumental: true,
      ai_description: 'A cinematic piano-led instrumental cover with grand piano lead, lush strings, a soaring cello solo, and slow emotional dynamic builds.',
      style_weight: 0.8, audio_weight: 0.55, weirdness: 0.25,
      custom_mode_pref: 'ai',
    },
  },
  {
    id: 'gospel-choir',
    name: 'Gospel Choir',
    emoji: '⛪',
    category: 'fusion',
    description: 'Full gospel choir with Hammond organ',
    fields: {
      title_suffix: '(Gospel Version)',
      genre: 'gospel soul',
      mood: 'uplifting, powerful, soulful',
      tags: 'full gospel choir, Hammond B3 organ, tambourine, soulful lead vocal, hand claps, key changes',
      negative_tags: 'electronic, lo-fi, dark',
      vocal_gender: 'f',
      instrumental: false,
      ai_description: 'A soulful gospel cover with a full choir, Hammond B3 organ, tambourine, hand claps, dramatic key changes, and a powerful female lead.',
      style_weight: 0.8, audio_weight: 0.5, weirdness: 0.3,
      custom_mode_pref: 'ai',
    },
  },
  {
    id: 'afrobeats',
    name: 'Afrobeats',
    emoji: '🥁',
    category: 'fusion',
    description: 'Modern afrobeats — log drums and shakers',
    fields: {
      title_suffix: '(Afrobeats Remix)',
      genre: 'afrobeats',
      mood: 'sunny, danceable, sensual',
      tags: 'log drums, shakers, talking drum, melodic bass, bright synths, afro percussion, smooth vocal',
      negative_tags: 'metal, lo-fi, dark',
      vocal_gender: 'm',
      instrumental: false,
      ai_description: 'A modern afrobeats cover with log drums, shakers, talking drums, melodic bass, bright synth stabs, and a smooth male lead vocal.',
      style_weight: 0.8, audio_weight: 0.45, weirdness: 0.35,
      custom_mode_pref: 'ai',
    },
  },
];

export const PRESET_CATEGORIES = [
  { id: 'all',     label: 'All' },
  { id: 'novelty', label: 'Novelty' },
  { id: 'genre',   label: 'Genre Flips' },
  { id: 'era',     label: 'Eras' },
  { id: 'fusion',  label: 'Fusions' },
];